import { lazy } from 'react';

export const Login = lazy(() => import('./Login'));
export const ForgotPassword = lazy(() => import('./ForgotPassword'));
export const ResetPassword = lazy(() => import('./ResetPassword'));
export const Dashboard = lazy(() => import('./Dashboard'));
export const Customers = lazy(() => import('./Customers'));
export const CustomerForm = lazy(() => import('./customers/CustomerForm'));
export const CustomerLedger = lazy(() => import('./customers/CustomerLedger'));
export const ArchivedCustomers = lazy(() => import('./customers/ArchivedCustomers'));
export const CreditLimitsTerms = lazy(() => import('./customers/CreditLimitsTerms'));
export const Suppliers = lazy(() => import('./Suppliers'));
export const ItemsList = lazy(() => import('./items/ItemsList'));
export const ItemDetail = lazy(() => import('./items/ItemDetail'));
export const ItemForm = lazy(() => import('./items/ItemForm'));
export const Categories = lazy(() => import('./items/Categories'));
export const Groups = lazy(() => import('./items/Groups'));
export const Brands = lazy(() => import('./items/Brands'));
export const PriceChannels = lazy(() => import('./items/PriceChannels'));
export const UnitManagement = lazy(() => import('./items/UnitManagement'));
export const StockOverview = lazy(() => import('./inventory/StockOverview'));
export const WarehouseList = lazy(() => import('./inventory/warehouses/WarehouseList'));
export const WarehouseDashboard = lazy(() => import('./inventory/warehouses/WarehouseDashboard'));
export const StockTransfers = lazy(() => import('./inventory/StockTransfers'));
export const TransferForm = lazy(() => import('./inventory/TransferForm'));
export const TransferDetail = lazy(() => import('./inventory/TransferDetail'));
export const StockPurchases = lazy(() => import('./inventory/StockPurchases'));
export const PurchaseForm = lazy(() => import('./inventory/PurchaseForm'));
export const PurchaseDetail = lazy(() => import('./inventory/PurchaseDetail'));
export const StockMovements = lazy(() => import('./inventory/StockMovements'));
export const StockCounts = lazy(() => import('./inventory/StockCounts'));
export const StockCountForm = lazy(() => import('./inventory/StockCountForm'));
export const StockCountDetail = lazy(() => import('./inventory/StockCountDetail'));
export const InventoryAnalytics = lazy(() => import('./inventory/InventoryAnalytics'));
export const InventoryReports = lazy(() => import('./inventory/InventoryReports'));
export const POS = lazy(() => import('./POS'));
export const Purchases = lazy(() => import('./Purchases'));
export const PurchaseReports = lazy(() => import('./purchases/PurchaseReports'));
export const PurchaseReturns = lazy(() => import('./purchases/PurchaseReturns'));
export const PurchaseReturnForm = lazy(() => import('./purchases/PurchaseReturnForm'));
export const PurchaseReturnDetail = lazy(() => import('./purchases/PurchaseReturnDetail'));
export const PurchasePayments = lazy(() => import('./purchases/PurchasePayments'));
export const PurchasePaymentForm = lazy(() => import('./purchases/PurchasePaymentForm'));
export const PurchaseRequisitions = lazy(() => import('./purchases/PurchaseRequisitions'));
export const RequestForQuotation = lazy(() => import('./purchases/RequestForQuotation'));
export const PurchaseOrders = lazy(() => import('./purchases/PurchaseOrders'));
export const PurchaseOrderForm = lazy(() => import('./purchases/PurchaseOrderForm'));
export const PurchaseOrderDetail = lazy(() => import('./purchases/PurchaseOrderDetail'));
export const GoodsReceiptNotes = lazy(() => import('./purchases/GoodsReceiptNotes'));
export const PurchaseControl = lazy(() => import('./purchases/PurchaseControl'));
export const ExpensePurchaseList = lazy(() => import('./purchases/ExpensePurchaseList'));
export const ExpensePurchaseForm = lazy(() => import('./purchases/ExpensePurchaseForm'));
export const ExpensePurchaseDetail = lazy(() => import('./purchases/ExpensePurchaseDetail'));
export const SupplierLedger = lazy(() => import('./suppliers/SupplierLedger'));
export const Reports = lazy(() => import('./Reports'));
export const Users = lazy(() => import('./Users'));
export const Roles = lazy(() => import('./Roles'));
export const Settings = lazy(() => import('./Settings'));
export const GlobalStrings = lazy(() => import('./admin/GlobalStrings'));
export const UnpostedInvoices = lazy(() => import('./pos/UnpostedInvoices'));
export const POSTerminals = lazy(() => import('./pos/POSTerminals'));
export const ShiftHistory = lazy(() => import('./pos/ShiftHistory'));
export const Taxes = lazy(() => import('./settings/Taxes'));
export const ReceiptPrintingSettings = lazy(() => import('./pos/ReceiptPrintingSettings'));
export const POSHotkeysShortcuts = lazy(() => import('./pos/POSHotkeysShortcuts'));
export const LoyaltyCustomers = lazy(() => import('./pos/LoyaltyCustomers'));
export const POSLoyaltySettings = lazy(() => import('./pos/POSLoyaltySettings'));
export const ChartOfAccounts = lazy(() => import('./accounting/ChartOfAccounts'));
export const AccountMappings = lazy(() => import('./accounting/AccountMappings'));
export const JournalEntries = lazy(() => import('./accounting/JournalEntries'));
export const GeneralLedger = lazy(() => import('./accounting/GeneralLedger'));
export const TrialBalance = lazy(() => import('./accounting/TrialBalance'));
export const ProfitAndLoss = lazy(() => import('./accounting/ProfitAndLoss'));
export const BalanceSheet = lazy(() => import('./accounting/BalanceSheet'));
export const SalesList = lazy(() => import('./sales/SalesList'));
export const SalesReturn = lazy(() => import('./sales/SalesReturn'));
export const SalesAnalytics = lazy(() => import('./sales/SalesAnalytics'));
export const CashInvoices = lazy(() => import('./sales/CashInvoices'));
export const CreditInvoices = lazy(() => import('./sales/CreditInvoices'));
export const ProformaInvoices = lazy(() => import('./sales/ProformaInvoices'));
export const TodaySalesSummary = lazy(() => import('./sales/TodaySalesSummary'));
export const TopSellingItems = lazy(() => import('./sales/TopSellingItems'));
export const PendingPayments = lazy(() => import('./sales/PendingPayments'));
export const SalesCreditControl = lazy(() => import('./sales/SalesCreditControl'));
export const OverdueInvoices = lazy(() => import('./sales/OverdueInvoices'));
export const SalesPayments = lazy(() => import('./sales/SalesPayments'));
export const ReceiveSalesPayment = lazy(() => import('./sales/ReceiveSalesPayment'));
export const SalesQuotations = lazy(() => import('./sales/SalesQuotations'));
export const SalesQuotationForm = lazy(() => import('./sales/SalesQuotationForm'));
export const SalesQuotationConvert = lazy(() => import('./sales/SalesQuotationConvert'));
export const SalesQuotationDetail = lazy(() => import('./sales/SalesQuotationDetail'));
export const SalesOrders = lazy(() => import('./sales/SalesOrders'));
export const SalesOrderForm = lazy(() => import('./sales/SalesOrderForm'));
export const SalesOrderConvert = lazy(() => import('./sales/SalesOrderConvert'));
export const SalesPriceLists = lazy(() => import('./sales/SalesPriceLists'));
export const SalesCustomerGroupPricing = lazy(() => import('./sales/SalesCustomerGroupPricing'));
export const SalesPromotions = lazy(() => import('./sales/SalesPromotions'));
export const SalesDiscountRules = lazy(() => import('./sales/SalesDiscountRules'));
export const SalesInvoiceForm = lazy(() => import('./sales/SalesInvoiceForm'));
export const ServiceSalesInvoice = lazy(() => import('./sales/ServiceSalesInvoice'));
export const ServiceInvoicesList = lazy(() => import('./sales/ServiceInvoicesList'));
export const ServiceInvoiceView = lazy(() => import('./sales/ServiceInvoiceView'));
export const SalesSummaryReport = lazy(() => import('./sales/SalesSummaryReport'));
export const SalesCashDashboard = lazy(() => import('./sales/cash/SalesCashDashboard'));
export const SalesCashRuns = lazy(() => import('./sales/cash/SalesCashRuns'));
export const SalesCashRunDetail = lazy(() => import('./sales/cash/SalesCashRunDetail'));
export const SalesCashVault = lazy(() => import('./sales/cash/SalesCashVault'));
export const SalesCashDeposits = lazy(() => import('./sales/cash/SalesCashDeposits'));
export const SalesCashReconciliation = lazy(() => import('./sales/cash/SalesCashReconciliation'));
export const SalesCashAudit = lazy(() => import('./sales/cash/SalesCashAudit'));
export const SuperAdminShell = lazy(() => import('./super-admin/SuperAdminShell'));
export const SuperAdminDashboard = lazy(() => import('./super-admin/SuperAdminDashboard'));
export const SuperAdminCompanies = lazy(() => import('./super-admin/SuperAdminCompanies'));
export const SuperAdminCompanyProfile = lazy(() => import('./super-admin/SuperAdminCompanyProfile'));
export const SuperAdminModules = lazy(() => import('./super-admin/SuperAdminModules'));
export const SuperAdminBroadcasts = lazy(() => import('./super-admin/SuperAdminBroadcasts'));
export const SuperAdminAudit = lazy(() => import('./super-admin/SuperAdminAudit'));
export const SuperAdminSupportSessions = lazy(() => import('./super-admin/SuperAdminSupportSessions'));
export const Departments = lazy(() => import('./hr/Departments').then(m => ({ default: m.Departments })));
export const Positions = lazy(() => import('./hr/Positions').then(m => ({ default: m.Positions })));
export const Employees = lazy(() => import('./hr/Employees').then(m => ({ default: m.Employees })));
export const Attendance = lazy(() => import('./hr/Attendance').then(m => ({ default: m.Attendance })));
export const Leaves = lazy(() => import('./hr/Leaves').then(m => ({ default: m.Leaves })));
export const Services = lazy(() => import('./services/Services').then(m => ({ default: m.Services })));
export const BomManagement = lazy(() => import('./production/BomManagement'));
export const ProductionOrders = lazy(() => import('./production/ProductionOrders'));

// Banking Module
export const BankAccounts = lazy(() => import('./bank/BankAccounts'));
export const BankReconciliation = lazy(() => import('./bank/BankReconciliation'));

// Aging Module
export const ARAging = lazy(() => import('./aging/ARAging'));
export const APAging = lazy(() => import('./aging/APAging'));

// Fixed Assets Module
export const FixedAssetsList = lazy(() => import('./accounting/fixed-assets/FixedAssetsList'));
export const FixedAssetDetail = lazy(() => import('./accounting/fixed-assets/FixedAssetDetail'));

// Setup Wizard
