export const PERMISSIONS = {
    // Dashboard
    DASHBOARD_VIEW: 'dashboard.view',

    // Inventory
    INVENTORY_VIEW: 'inventory.view',
    INVENTORY_CREATE: 'inventory.create',
    INVENTORY_EDIT: 'inventory.edit',
    INVENTORY_DELETE: 'inventory.delete',
    INVENTORY_ADJUST: 'inventory.adjust',
    INVENTORY_TRANSFER: 'inventory.transfer',
    INVENTORY_AUDIT: 'inventory.audit',
    INVENTORY_VIEW_LEDGER: 'inventory.viewLedger',
    INVENTORY_VIEW_ANALYTICS: 'inventory.viewAnalytics',

    // POS
    POS_VIEW: 'pos.view',
    POS_CREATE: 'pos.create',
    POS_EDIT: 'pos.edit',
    POS_DELETE: 'pos.delete',
    POS_ACCESS: 'pos.access',
    POS_SELL: 'pos.sell',
    POS_REFUND: 'pos.refund',
    POS_VOID: 'pos.void',
    POS_DISCOUNT: 'pos.discount',
    POS_MANAGE_TERMINALS: 'pos.manageTerminals',
    POS_CLOSE_SHIFT: 'pos.closeShift',
    POS_VIEW_SHIFTS: 'pos.viewShifts',
    POS_VIEW_OWN_SHIFTS: 'pos.viewOwnShifts',
    POS_TERMINAL_ONLY: 'pos.terminalOnly',

    // Purchases
    PURCHASE_VIEW: 'purchase.view',
    PURCHASE_CREATE: 'purchase.create',
    PURCHASE_EDIT: 'purchase.edit',
    PURCHASE_DELETE: 'purchase.delete',
    PURCHASE_RETURN: 'purchase.return',
    PURCHASE_PAYMENT: 'purchase.payment',
    PURCHASE_CONTROL: 'purchase.control',

    // Suppliers
    SUPPLIER_VIEW: 'supplier.view',
    SUPPLIER_CREATE: 'supplier.create',
    SUPPLIER_EDIT: 'supplier.edit',
    SUPPLIER_DELETE: 'supplier.delete',

    // Sales
    SALES_VIEW: 'sales.view',
    SALES_CREATE: 'sales.create',
    SALES_EDIT: 'sales.edit',
    SALES_DELETE: 'sales.delete',
    SALES_RETURN: 'sales.return',
    SALES_QUOTATION_VIEW: 'sales.quotationView',
    SALES_QUOTATION_CREATE: 'sales.quotationCreate',
    SALES_QUOTATION_CONVERT: 'sales.quotationConvert',
    SALES_ORDER_VIEW: 'sales.orderView',
    SALES_ORDER_CREATE: 'sales.orderCreate',
    SALES_ORDER_FULFILL: 'sales.orderFulfill',
    SALES_INVOICE_CASH: 'sales.invoiceCash',
    SALES_INVOICE_CREDIT: 'sales.invoiceCredit',
    SALES_INVOICE_PROFORMA: 'sales.invoiceProforma',
    SALES_PAYMENT_VIEW: 'sales.paymentView',
    SALES_PAYMENT_RECEIVE: 'sales.paymentReceive',
    SALES_PAYMENT_ADVANCE: 'sales.paymentAdvance',
    SALES_PAYMENT_ALLOCATE: 'sales.paymentAllocate',
    SALES_PRICING_MANAGE: 'sales.pricingManage',
    SALES_DELIVERY_MANAGE: 'sales.deliveryManage',
    SALES_CREDIT_CONTROL: 'sales.creditControl',
    SALES_CUSTOMER_LEDGER: 'sales.customerLedger',
    SALES_APPROVALS: 'sales.approvals',
    SALES_CASH_VIEW: 'sales.cashView',
    SALES_CASH_RUN_CREATE: 'sales.cashRunCreate',
    SALES_CASH_PICKUP: 'sales.cashPickup',
    SALES_CASH_VAULT: 'sales.cashVault',
    SALES_CASH_DEPOSIT: 'sales.cashDeposit',
    SALES_CASH_RECONCILE: 'sales.cashReconcile',
    SALES_CASH_AUDIT: 'sales.cashAudit',

    // CRM
    CRM_VIEW: 'crm.view',
    CRM_CREATE: 'crm.create',
    CRM_EDIT: 'crm.edit',
    CRM_DELETE: 'crm.delete',
    CRM_MANAGE_GROUPS: 'crm.manageGroups',

    // Products
    PRODUCT_VIEW: 'product.view',
    PRODUCT_CREATE: 'product.create',
    PRODUCT_EDIT: 'product.edit',
    PRODUCT_DELETE: 'product.delete',
    PRODUCT_EDIT_ITEM: 'product.editItem',
    PRODUCT_EDIT_PRICING: 'product.editPricing',
    PRODUCT_EDIT_MASTER: 'product.editMaster',
    PRODUCT_MANAGE_PRICING: 'product.managePricing',

    // Accounting
    ACCOUNTING_VIEW: 'accounting.view',
    ACCOUNTING_CREATE: 'accounting.create',
    ACCOUNTING_EDIT: 'accounting.edit',
    ACCOUNTING_DELETE: 'accounting.delete',
    ACCOUNTING_POST: 'accounting.post',
    ACCOUNTING_CLOSE_PERIOD: 'accounting.closePeriod',
    ACCOUNTING_EXPENSE: 'accounting.expense',

    // Reports
    REPORTS_VIEW: 'reports.view',
    REPORTS_EXPORT: 'reports.export',

    // Admin
    ADMIN_MANAGE_USERS: 'admin.manageUsers',
    ADMIN_MANAGE_ROLES: 'admin.manageRoles',
    ADMIN_MANAGE_SETTINGS: 'admin.manageSettings',
    ADMIN_MANAGE_STRINGS: 'admin.manageStrings',
    ADMIN_MANAGE_BRANCHES: 'admin.manageBranches',
    ADMIN_VIEW_AUDIT: 'admin.viewAudit',

    // Application
    APP_VIEW_SIDEBAR: 'app.viewSidebar',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_SYSTEM_ROLES = [
    {
        name: 'Admin',
        permissions: ALL_PERMISSIONS,
    },
    {
        name: 'Manager',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.DASHBOARD_VIEW,
            PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER, PERMISSIONS.INVENTORY_AUDIT,
            PERMISSIONS.POS_ACCESS, PERMISSIONS.POS_SELL, PERMISSIONS.POS_REFUND, PERMISSIONS.POS_VOID, PERMISSIONS.POS_DISCOUNT, PERMISSIONS.POS_VIEW_SHIFTS, PERMISSIONS.POS_CLOSE_SHIFT,
            PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_RETURN, PERMISSIONS.PURCHASE_PAYMENT,
            PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.SUPPLIER_CREATE, PERMISSIONS.SUPPLIER_EDIT, PERMISSIONS.SUPPLIER_DELETE,
            PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.ACCOUNTING_EXPENSE,
            PERMISSIONS.CRM_VIEW, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_EDIT, PERMISSIONS.CRM_DELETE,
            PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_EDIT, PERMISSIONS.PRODUCT_DELETE, PERMISSIONS.PRODUCT_MANAGE_PRICING,
            PERMISSIONS.PRODUCT_EDIT_ITEM, PERMISSIONS.PRODUCT_EDIT_PRICING, PERMISSIONS.PRODUCT_EDIT_MASTER,
            PERMISSIONS.REPORTS_VIEW,
            PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_RETURN,
            PERMISSIONS.SALES_QUOTATION_VIEW, PERMISSIONS.SALES_QUOTATION_CREATE, PERMISSIONS.SALES_QUOTATION_CONVERT,
            PERMISSIONS.SALES_ORDER_VIEW, PERMISSIONS.SALES_ORDER_CREATE, PERMISSIONS.SALES_ORDER_FULFILL,
            PERMISSIONS.SALES_INVOICE_CASH, PERMISSIONS.SALES_INVOICE_CREDIT, PERMISSIONS.SALES_INVOICE_PROFORMA,
            PERMISSIONS.SALES_PAYMENT_VIEW, PERMISSIONS.SALES_PAYMENT_RECEIVE, PERMISSIONS.SALES_PAYMENT_ADVANCE, PERMISSIONS.SALES_PAYMENT_ALLOCATE,
            PERMISSIONS.SALES_PRICING_MANAGE, PERMISSIONS.SALES_DELIVERY_MANAGE, PERMISSIONS.SALES_CREDIT_CONTROL, PERMISSIONS.SALES_CUSTOMER_LEDGER, PERMISSIONS.SALES_APPROVALS,
            PERMISSIONS.SALES_CASH_VIEW, PERMISSIONS.SALES_CASH_RUN_CREATE, PERMISSIONS.SALES_CASH_PICKUP, PERMISSIONS.SALES_CASH_VAULT, PERMISSIONS.SALES_CASH_DEPOSIT, PERMISSIONS.SALES_CASH_RECONCILE, PERMISSIONS.SALES_CASH_AUDIT,
        ],
    },
    {
        name: 'Operations Associate',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.DASHBOARD_VIEW,
            PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
            PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_RETURN, PERMISSIONS.PURCHASE_PAYMENT,
            PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.SUPPLIER_CREATE, PERMISSIONS.SUPPLIER_EDIT,
            PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_EDIT, PERMISSIONS.PRODUCT_MANAGE_PRICING,
            PERMISSIONS.PRODUCT_EDIT_ITEM, PERMISSIONS.PRODUCT_EDIT_PRICING, PERMISSIONS.PRODUCT_EDIT_MASTER,
            PERMISSIONS.CRM_VIEW, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_EDIT,
            PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE,
            PERMISSIONS.SALES_ORDER_VIEW, PERMISSIONS.SALES_ORDER_CREATE, PERMISSIONS.SALES_ORDER_FULFILL,
            PERMISSIONS.SALES_QUOTATION_VIEW, PERMISSIONS.SALES_QUOTATION_CREATE, PERMISSIONS.SALES_QUOTATION_CONVERT,
            PERMISSIONS.SALES_INVOICE_CASH, PERMISSIONS.SALES_INVOICE_CREDIT,
            PERMISSIONS.SALES_PAYMENT_VIEW, PERMISSIONS.SALES_PAYMENT_RECEIVE, PERMISSIONS.SALES_PAYMENT_ADVANCE, PERMISSIONS.SALES_PAYMENT_ALLOCATE,
            PERMISSIONS.SALES_DELIVERY_MANAGE, PERMISSIONS.SALES_CREDIT_CONTROL, PERMISSIONS.SALES_CUSTOMER_LEDGER,
            PERMISSIONS.SALES_CASH_VIEW, PERMISSIONS.SALES_CASH_RUN_CREATE, PERMISSIONS.SALES_CASH_PICKUP,
            PERMISSIONS.REPORTS_VIEW,
        ],
    },
    {
        name: 'Accountant',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.DASHBOARD_VIEW,
            PERMISSIONS.ACCOUNTING_VIEW, PERMISSIONS.ACCOUNTING_POST, PERMISSIONS.ACCOUNTING_CLOSE_PERIOD, PERMISSIONS.ACCOUNTING_EXPENSE,
            PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_RETURN, PERMISSIONS.PURCHASE_PAYMENT,
            PERMISSIONS.SALES_CASH_VIEW, PERMISSIONS.SALES_CASH_VAULT, PERMISSIONS.SALES_CASH_DEPOSIT, PERMISSIONS.SALES_CASH_RECONCILE, PERMISSIONS.SALES_CASH_AUDIT,
            PERMISSIONS.REPORTS_VIEW,
            PERMISSIONS.CRM_VIEW,
            PERMISSIONS.PRODUCT_VIEW,
            PERMISSIONS.INVENTORY_VIEW,
        ],
    },
    {
        name: 'Sales Associate',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.DASHBOARD_VIEW,
            PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE, PERMISSIONS.SALES_RETURN,
            PERMISSIONS.SALES_QUOTATION_VIEW, PERMISSIONS.SALES_QUOTATION_CREATE, PERMISSIONS.SALES_QUOTATION_CONVERT,
            PERMISSIONS.SALES_ORDER_VIEW, PERMISSIONS.SALES_ORDER_CREATE, PERMISSIONS.SALES_ORDER_FULFILL,
            PERMISSIONS.SALES_INVOICE_CASH, PERMISSIONS.SALES_INVOICE_CREDIT, PERMISSIONS.SALES_INVOICE_PROFORMA,
            PERMISSIONS.SALES_PAYMENT_VIEW, PERMISSIONS.SALES_PAYMENT_RECEIVE, PERMISSIONS.SALES_PAYMENT_ADVANCE, PERMISSIONS.SALES_PAYMENT_ALLOCATE,
            PERMISSIONS.SALES_PRICING_MANAGE, PERMISSIONS.SALES_DELIVERY_MANAGE, PERMISSIONS.SALES_CREDIT_CONTROL, PERMISSIONS.SALES_CUSTOMER_LEDGER,
            PERMISSIONS.SALES_CASH_VIEW, PERMISSIONS.SALES_CASH_RUN_CREATE, PERMISSIONS.SALES_CASH_PICKUP,
            PERMISSIONS.CRM_VIEW, PERMISSIONS.CRM_CREATE, PERMISSIONS.CRM_EDIT,
            PERMISSIONS.POS_ACCESS, PERMISSIONS.POS_SELL, PERMISSIONS.POS_DISCOUNT, PERMISSIONS.POS_REFUND,
            PERMISSIONS.PRODUCT_VIEW,
            PERMISSIONS.REPORTS_VIEW,
        ],
    },
    {
        name: 'Cashier',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.POS_ACCESS, PERMISSIONS.POS_SELL, PERMISSIONS.POS_DISCOUNT, PERMISSIONS.POS_CLOSE_SHIFT, PERMISSIONS.POS_VIEW_OWN_SHIFTS, PERMISSIONS.POS_TERMINAL_ONLY,
            PERMISSIONS.SALES_VIEW, PERMISSIONS.SALES_CREATE,
            PERMISSIONS.PRODUCT_VIEW,
            PERMISSIONS.CRM_VIEW, PERMISSIONS.CRM_CREATE,
            PERMISSIONS.INVENTORY_VIEW,
        ],
    },
    {
        name: 'Shopkeeper',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.DASHBOARD_VIEW,
            PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER, PERMISSIONS.INVENTORY_AUDIT, PERMISSIONS.INVENTORY_VIEW_LEDGER,
            PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_VIEW, PERMISSIONS.PURCHASE_RETURN,
            PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_EDIT,
            PERMISSIONS.PRODUCT_EDIT_ITEM, PERMISSIONS.PRODUCT_EDIT_PRICING, PERMISSIONS.PRODUCT_EDIT_MASTER,
            PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.SUPPLIER_CREATE,
            PERMISSIONS.REPORTS_VIEW,
        ],
    },
    {
        name: 'Viewer',
        permissions: [
            PERMISSIONS.APP_VIEW_SIDEBAR,
            PERMISSIONS.DASHBOARD_VIEW,
            PERMISSIONS.CRM_VIEW,
            PERMISSIONS.PRODUCT_VIEW,
            PERMISSIONS.INVENTORY_VIEW,
            PERMISSIONS.PURCHASE_VIEW,
            PERMISSIONS.SUPPLIER_VIEW,
            PERMISSIONS.SALES_VIEW,
            PERMISSIONS.ACCOUNTING_VIEW,
            PERMISSIONS.REPORTS_VIEW,
        ],
    },
] as const;

export const SYSTEM_ROLE_NAMES = DEFAULT_SYSTEM_ROLES.map((role) => role.name);
export function isSystemRoleName(name: string) {
    return SYSTEM_ROLE_NAMES.some((systemName) => systemName.toLowerCase() === name.trim().toLowerCase());
}

// Predefined role templates
export const ROLE_TEMPLATES = {
    ADMIN: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Admin')!.permissions,
    MANAGER: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Manager')!.permissions,
    OPERATIONS_ASSOCIATE: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Operations Associate')!.permissions,
    ACCOUNTANT: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Accountant')!.permissions,
    SALES_ASSOCIATE: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Sales Associate')!.permissions,
    CASHIER: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Cashier')!.permissions,
    SHOPKEEPER: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Shopkeeper')!.permissions,
    VIEWER: DEFAULT_SYSTEM_ROLES.find((r) => r.name === 'Viewer')!.permissions,
};
